export const  UPDATE_PROFILE = "UPDATE_PROFILE";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const ADD_SKILL = "ADD_SKILL";
export const UPDATE_CURRENT_TAB = "UPDATE_CURRENT_TAB";
export const UPDATE_CURRENT_EDUCATION = "UPDATE_CURRENT_EDUCATION";
export const UPDATE_CURRENT_EXPERIENCE = "UPDATE_CURRENT_EXPERIENCE";